// Auto-generated by sdk/generate-types.ts — do not edit manually

import type * as Y from 'yjs';

import type * as React from 'react';

import type { JSX } from 'react';

import type { LucideIcon } from 'lucide-react';

/**
 * Manual SDK declarations for globals that cannot be auto-generated
 * from the barrel file. These are prepended to the generated index.d.ts.
 */

/** Register a plugin with the host. Called synchronously when the plugin IIFE executes. */
export declare function registerPlugin(plugin: PluginInstance): void;

/** The application's base URL path (e.g. '/elephant'). Available immediately on script load. */
export declare const BASE_URL: string;

/**
 * Slate editor access — available inside injection points rendered within
 * a Slate/Textbit editor context (e.g. the Editor view footer).
 */
export { useSlate } from 'slate-react';
export { Editor as SlateEditor, Range as SlateRange } from 'slate';

export declare function useYDocument<T>(id: string, options?: { data?: unknown; skipIndexedDB?: boolean | undefined; visibility?: boolean | undefined; rootMap?: string | undefined; ignoreChangeKeys?: string[] | undefined; } | undefined): YDocument<T>;

export interface YDocument<T> {
  id: string;
  ele: T;
  ctx: Y.Map<unknown>;
  connected: boolean;
  synced: boolean;
  online: boolean;
  visibility: boolean;
  isInProgress: boolean;
  setIsInProgress: (isInProgress: boolean) => void;
  isChanged: boolean;
  setIsChanged: (isChanged: boolean) => void;
  transact: (f: (arg0: Y.Map<T>, arg1: Y.Transaction) => void) => void;
  send: (key: string, payload: unknown) => void;
  provider: unknown | null;
  user: unknown | null;
}

export declare function useYValue<T>(yContainer: Y.Map<unknown> | Y.Array<unknown> | undefined, relativePath: string | [string, ...(string | number)[]], raw: boolean): [T | undefined, (newValue: T) => void];

export declare const ViewHeader: {
  Root: (__0: { className?: string | undefined; asDialog?: boolean | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
  Title: (__0: { name: string; title: string; short?: string | undefined; icon?: LucideIcon | undefined; iconColor?: string | undefined; asDialog?: boolean | undefined; ydoc?: YDocument<Y.Map<unknown>> | undefined; preview?: boolean | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
  Content: (__0: { children?: React.ReactNode; } & { className?: string | undefined; }) => JSX.Element;
  Action: (__0: { children?: React.ReactNode; } & { ydoc?: YDocument<Y.Map<unknown>> | undefined; onDialogClose?: (() => void) | undefined; asDialog?: boolean | undefined; }) => JSX.Element;
  RemoteUsers: (__0: { children?: React.ReactNode; } & { ydoc: YDocument<Y.Map<unknown>>; }) => JSX.Element;
};

export declare const View: {
  Root: (__0: { className?: string | undefined; asDialog?: boolean | undefined; tab?: string | undefined; onTabChange?: React.Dispatch<React.SetStateAction<string>> | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
  Content: (__0: { className?: string | undefined; variant?: "default" | "grid" | "no-scroll" | undefined; columns?: number | undefined; style?: React.CSSProperties | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
  Column: (__0: { className?: string | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
  Footer: (__0: { className?: string | undefined; } & { children?: React.ReactNode; }) => JSX.Element;
};

export declare const TextBox: ({ icon: Icon, value, onChange, ...props }: { ydoc: YDocument<Y.Map<unknown>>; value: Y.XmlText | undefined; disabled?: boolean | undefined; icon?: React.ReactNode; placeholder?: string | undefined; className?: string | undefined; singleLine?: boolean | undefined; autoFocus?: boolean | undefined; countCharacters?: boolean | undefined; spellcheck?: boolean | undefined; onBlur?: React.FocusEventHandler<HTMLDivElement> | undefined; onFocus?: React.FocusEventHandler<HTMLDivElement> | undefined; onChange?: ((arg: unknown[]) => void) | undefined; }) => JSX.Element;

export declare const Form: {
  Root: (__0: { children?: React.ReactNode; } & { asDialog?: boolean | undefined; className?: string | undefined; }) => JSX.Element;
  Content: (props: Record<string, unknown>) => React.ReactNode;
  Title: (__0: Record<string, unknown>) => JSX.Element;
  Group: (__0: Record<string, unknown> & { icon?: LucideIcon | undefined; }) => JSX.Element;
  Footer: (__0: Record<string, unknown> & { className?: string | undefined; }) => JSX.Element | null;
  Submit: (__0: Record<string, unknown> & { documentId?: string | undefined; onDialogClose?: ((id: string, title: string) => void) | undefined; onSubmit?: (() => void | Promise<void>) | undefined; onSecondarySubmit?: (() => void | Promise<void>) | undefined; onTertiarySubmit?: (() => void | Promise<void>) | undefined; onDocumentCreated?: (() => void) | undefined; onReset?: (() => void) | undefined; disableOnSubmit?: boolean | undefined; }) => JSX.Element | null;
  Table: (__0: Record<string, unknown> & { className?: string | undefined; }) => JSX.Element;
};

export declare function resolveEventOptions(event: React.MouseEvent<Element, MouseEvent> | KeyboardEvent): ExecuteOptions | null;

export interface ExecuteOptions {
  target?: 'self' | 'blank' | 'last' | undefined;
  keepFocus?: boolean | undefined;
}

export declare const InjectionPoint: ({ id, ydoc, data, className, children }: InjectionPointProps) => JSX.Element | null;

export interface InjectionPointProps {
  id: string;
  ydoc?: YDocument<Y.Map<unknown>> | undefined;
  data?: Record<string, unknown> | undefined;
  className?: string | undefined;
  children?: React.ReactNode;
}

export interface InjectionPointRendererProps {
  ydoc?: YDocument<Y.Map<unknown>> | undefined;
  data?: Record<string, unknown> | undefined;
  children?: React.ReactNode;
}

export interface ViewProps {
  id?: string | null | undefined;
  planningId?: string | null | undefined;
  version?: string | undefined;
  asDialog?: boolean | undefined;
  onDialogClose?: ((id?: string | undefined, title?: string | undefined) => void) | undefined;
  onDocumentCreated?: (() => void) | undefined;
  from?: string | undefined;
  source?: string | undefined;
  className?: string | undefined;
  payload?: unknown;
  autoFocus?: boolean | undefined;
  setOpen?: ((open?: boolean | undefined) => boolean) | undefined;
  preview?: boolean | undefined;
}

export interface ViewMetadata {
  name: string;
  path: string;
  widths: Record<string, number>;
}

export interface ViewRegistryItem {
  meta: ViewMetadata;
  component: React.FC<ViewProps>;
}

export interface ActivityDefinition {
  title: string;
  icon?: LucideIcon | undefined;
  viewRouteFunc: ViewRouteFunc;
  matchFunc?: unknown;
}

export type ViewRouteFunc = (
  docId: string,
  args?: Record<string, unknown>
) => Promise<ResolvedRoute>;

export interface ResolvedRoute {
  viewName: string;
  props: ViewProps;
  target?: 'self' | 'blank' | 'last' | undefined;
}

export interface PluginInstance {
  activate: (context: PluginContext) => void | (() => void);
}

export interface PluginContext {
  documentActivity: { register: (docType: string, activityId: string, definition: ActivityDefinition) => () => void; };
  viewRegistry: { register: (name: string, item: ViewRegistryItem) => () => void; };
  injectionPoints: { register: (pointId: string, rendererId: string, renderer: React.FC<InjectionPointRendererProps>) => () => void; };
}
